EfficientNet: None
DinoV2: ./dinov2-base
CLIPSegForImageSegmentation: ./clipseg-rd64-refined
CLIPSegModel: ./clipseg-rd64-refined
SAM: ./sam_vit_b_01ec64.pth
Unet++: ./unetpp_base.ckpt
DeepCrack: ./deepcrack_base.pth
SAMAdapter: ./adsam_base/_cod-sam-vit-b/adsam.pth